## SCARA - PRR Variant 3 - 3-DOF

### Imported Libraries

In [1]:
import numpy as np
import math

### Forward Kinematics

In [ ]:
# link lengths in cm
a1 = float(input("a1 = ")) # For testing, 55 mm
a2 = float(input("a2 = ")) # For testing, 60 mm
a3 = float(input("a3 = ")) # For testing, 30 mm
a4 = float(input("a4 = ")) # For testing, 60 mm

d1 = float(input("d1 = ")) # For testing, 100 mm
T2 = float(input("T2 = ")) # For testing, 0 degrees
T3 = float(input("T3 = ")) # For testing, 0 degrees

T2 = (T2/180.0)*np.pi # Theta 2 in radians
T3 = (T3/180.0)*np.pi # Theta 3 in radians

PT = [[(0.0/180.0)*np.pi,(0.0/180.0)*np.pi,0,a1+d1],
      [T2,(0.0/180.0)*np.pi,a2,0],
      [T3,(0.0/180.0)*np.pi,a4,a3]]

i = 0
H0_1 = [[np.cos(PT[i][0]),-np.sin(PT[i][0])*np.cos(PT[i][1]),np.sin(PT[i][0])*np.sin(PT[i][1]),PT[i][2]*np.cos(PT[i][0])],
        [np.sin(PT[i][0]),np.cos(PT[i][0])*np.cos(PT[i][1]),-np.cos(PT[i][0])*np.sin(PT[i][1]),PT[i][2]*np.sin(PT[i][0])],
        [0,np.sin(PT[i][1]),np.cos(PT[i][1]),PT[i][3]],
        [0,0,0,1]]

i = 1
H1_2 = [[np.cos(PT[i][0]),-np.sin(PT[i][0])*np.cos(PT[i][1]),np.sin(PT[i][0])*np.sin(PT[i][1]),PT[i][2]*np.cos(PT[i][0])],
        [np.sin(PT[i][0]),np.cos(PT[i][0])*np.cos(PT[i][1]),-np.cos(PT[i][0])*np.sin(PT[i][1]),PT[i][2]*np.sin(PT[i][0])],
        [0,np.sin(PT[i][1]),np.cos(PT[i][1]),PT[i][3]],
        [0,0,0,1]]

i = 2
H2_3 = [[np.cos(PT[i][0]),-np.sin(PT[i][0])*np.cos(PT[i][1]),np.sin(PT[i][0])*np.sin(PT[i][1]),PT[i][2]*np.cos(PT[i][0])],
        [np.sin(PT[i][0]),np.cos(PT[i][0])*np.cos(PT[i][1]),-np.cos(PT[i][0])*np.sin(PT[i][1]),PT[i][2]*np.sin(PT[i][0])],
        [0,np.sin(PT[i][1]),np.cos(PT[i][1]),PT[i][3]],
        [0,0,0,1]]


H0_1 = np.matrix(H0_1) 
#print("H0_1=")
#print(H0_1)

H1_2 = np.matrix(H1_2) 
#print("H1_2=")
#print(H1_2)

H2_3 = np.matrix(H2_3)
#print("H2_3=")
#print(H2_3)

H0_2 = np.dot(H0_1,H1_2)
H0_3 = np.dot(H0_2,H2_3)
print("H0_3=")
print(np.matrix(H0_3))


In [ ]:
print("H0_2 = ")
print(np.matrix(H0_2))

### Position Vectors

In [81]:
X0_3 = H0_3[0,3]
print("X = ", X0_3)
Y0_3 =H0_3[1,3]
print("Y = ", Y0_3)
Z0_3 =H0_3[2,3]
print("Z = ", Z0_3)

X =  101.11064688440584
Y =  4.414586181062756
Z =  135.0


### Jacobian Matrix

### 1. Linear / Prismatic Vectors

In [82]:
Z_1 = [[0],[0],[1]] # The [0,0,1] vector

# Row 1 - 3, Column 1

J1 = [[1,0,0],[0,1,0],[0,0,1]]
J1 = np.dot(J1,Z_1)
J1 = np.matrix(J1)
print('J1 = ')
print(np.matrix(J1))

J1 = 
[[0]
 [0]
 [1]]


In [83]:
# Row 1 - 3, Column 2

J2a = H0_1[0:3,0:3]
J2a = np.dot(J2a,Z_1)
#print("J2a = ")
#print(J2a)

J2b_1 = H0_3[0:3,3:]
J2b_1 = np.matrix(J2b_1)
# print(J2b_1)

J2b_2 = H0_1[0:3,3:]
J2b_2 = np.matrix(J2b_2)
# print(J2b_2)

J2b = J2b_1 - J2b_2
#print("J2b = ")
#print(J2b)

J2 = [[(J2a[1,0]*J2b[2,0])-(J2a[2,0]*J2b[1,0])],
     [(J2a[2,0]*J2b[0,0])-(J2a[0,0]*J2b[2,0])],
     [(J2a[0,0]*J2b[1,0])-(J2a[1,0]*J2b[0,0])]]
print("J2 = ")
print(np.matrix(J2))


J2 = 
[[ -4.41458618]
 [101.11064688]
 [  0.        ]]


In [84]:
# Row 1 - 3, Column 3

J3a = H0_2[0:3,0:3]
J3a = np.dot(J3a,Z_1)
#print("J3a = ")
#print(J3a)

J3b_1 = H0_3[0:3,3:]
J3b_1 = np.matrix(J3b_1)

J3b_2 = H0_2[0:3,3:]
J3b_2 = np.matrix(J3b_2)

J3b = J3b_1 - J3b_2
#print('J3b = ')
#print(J3b)

J3 = [[(J3a[1,0]*J3b[2,0])-(J3a[2,0]*J3b[1,0])],
     [(J3a[2,0]*J3b[0,0])-(J3a[0,0]*J3b[2,0])],
     [(J3a[0,0]*J3b[1,0])-(J3a[1,0]*J3b[0,0])]]
print("J3 = ")
print(np.matrix(J3))


J3 = 
[[30.        ]
 [51.96152423]
 [-0.        ]]


### 2. Rotation / Orientation Vectors

In [85]:
J4 = [[0],[0],[0]]
J4 = np.matrix(J4)
print("J4 = ")
print(J4)

J5 = H0_1[0:3,0:3]
J5 = np.dot(J5,Z_1)
J5 = np.matrix(J5)
print("J5 = ")
print(J5)

J6 = H0_1[0:3,0:3]
J6 = np.dot(J6,Z_1)
J6 = np.matrix(J6)
print("J6 = ")
print(J6)

J4 = 
[[0]
 [0]
 [0]]
J5 = 
[[0.]
 [0.]
 [1.]]
J6 = 
[[0.]
 [0.]
 [1.]]


### 3. Concatenated Jacobian Matrix

In [86]:
JM1 = np.concatenate((J1,J2,J3),1)
# print(JM1)
JM2 =np.concatenate((J4,J5,J6),1)
# print(JM2)

J = np.concatenate((JM1,JM2),0)
print("J = ")
print(J)

J = 
[[  0.          -4.41458618  30.        ]
 [  0.         101.11064688  51.96152423]
 [  1.           0.          -0.        ]
 [  0.           0.           0.        ]
 [  0.           0.           0.        ]
 [  0.           1.           1.        ]]


### Singularities

In [87]:
# singularity = Det(J)
# np.linalg.det(M)
# Let JM1 become the 3x3 position matrix for obtaining the Determinant

DJ = np.linalg.det(JM1)
print("DJ = ",DJ)



DJ =  -3262.708033331942


### Inverse Velocity

In [88]:
# Inv(J)

IV = np.linalg.inv(JM1)
print("IV = ")
print(IV)

IV = 
[[ 0.          0.          1.        ]
 [-0.01592589  0.00919482  0.        ]
 [ 0.03098979  0.00135304  0.        ]]


### Torque-Force Analysis

In [90]:
# Transpose of Jacobian Matrix

TJ = np.transpose(JM1)
print("TJ = ")
print(TJ)

TJ = 
[[  0.           0.           1.        ]
 [ -4.41458618 101.11064688   0.        ]
 [ 30.          51.96152423  -0.        ]]


### Inverse Kinematics

In [ ]:
phi2 = (np.arctan(Y0_3/X0_3))
r1 = math.sqrt((X0_3**2)+(Y0_3**2))
phi1 = np.arccos((a4**2-r1**2-a2**2)/(-2.0*r1*a2))
Th2 = ((phi2-phi1)*180.0/np.pi)
phi3 = (np.arccos((r1**2-a2**2-a4**2)/(-2.0*a2*a4)))
Th3 = 180 - phi3*(180.0/np.pi)
d1 = Z0_3 - a1 - a3

print("d1=")
print(d1)

print("Th2=")
print(Th2)

print("Th3")
print(Th3)